### ISSUE TITLE
error when grabbing groups

### ISSUE THREAD

**Issue by jstacoder** [WMInfoTech/python-msgraph#1]
when im grabbing my groups, im getting an error:
`KeyError: 'group_types'` 
seems to be because its trying to grab the attr `group_types` from the response data, but i see with a little debugging it is actually coming over as `groupTypes` which makes sense since its like the other values.... does this work for you @pcfens  or @dpfens ? if not id love to contribute the fix (since its such an easy one)

**Comment by dpfens** [comment]
@jstacoder Thank you for fixing this.  Your change was just merged into the `master` branch.

**Comment by dpfens** [comment]
@jstacoder I just pushed a new version (0.2.6) with your change to PyPi.
